### PR TITLE
Feature/update datasets

### PR DESCRIPTION
**Pull request by sam-medispring**
- Update of all datasets
- Fix scraper for DE datasets (xlsx no longer available, changed to csv)

### CODE REVIEW

**Comment by alfaproject** [comment]
I'd love for this to be merged ^_^

**Comment by wsslfnstr** [comment]
@sigalor Could you please merge this pull request?

**Comment by rleroi** [comment]
We've forked this repo and merged both PR's to it.
https://www.npmjs.com/package/@mogelijk_technologies/iban-to-bic

**Comment by sigalor** [comment]
Perfect, also merged it here now!

**Comment by sigalor** [comment]
And also published 1.4.0 on NPM.

**Pull request merged**
